server:
  port: 2673


spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      max-lifetime: 160000

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka

#token:
#  expiration_time: 86400000
#  secret: secretkeydsfdafajfajioewjfkljasdklfjisadjfiosadjfkjaioejfkajfioejkfajifojaisjfklejklafjeiajfaljfkdsjfai


logging:
  level:
    com.example.orderservice: DEBUG

